<?php

/**
 * @file
 * Hooks and callbacks for this module.
 */

/**
 * Implements hook_theme().
 */
function islandora_video_theme($existing, $type, $theme, $path) {
  return [
    'islandora_video' => [
      'file' => 'theme/theme.inc',
      'pattern' => 'islandora_video__',
      'variables' => ['object' => NULL],
    ],
  ];
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_video_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_video');
  // Video Content Model.
  $video_content_model = $connection->repository->constructObject('islandora:sp_videoCModel');
  $video_content_model->owner = 'fedoraAdmin';
  $video_content_model->label = 'Islandora Video Content Model';
  $video_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $video_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'application/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_video_ds_composite_model.xml", FALSE);
  $video_content_model->ingestDatastream($datastream);
  // Video Collection.
  $video_collection = $connection->repository->constructObject('islandora:video_collection');
  $video_collection->owner = 'fedoraAdmin';
  $video_collection->label = 'Video Collection';
  $video_collection->models = 'islandora:collectionCModel';
  $video_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $video_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'application/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_video_collection_policy.xml", FALSE);
  $video_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $video_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $video_collection->ingestDatastream($datastream);
  return [
    'islandora_video' => [
      'title' => 'Islandora Video',
      'objects' => [
        $video_content_model,
        $video_collection,
      ],
    ],
  ];
}

/**
 * Implements hook_xml_form_builder_forms().
 */
function islandora_video_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_video');
  return [
    'Video MODS form' => [
      'form_file' => "$module_path/xml/islandora_video_form_mods.xml",
    ],
  ];
}

/**
 * Implements hook_xml_form_builder_form_associations().
 */
function islandora_video_xml_form_builder_form_associations() {
  return [
    'islandora_video_mods_form' => [
      'content_model' => 'islandora:sp_videoCModel',
      'form_name' => 'Video MODS form',
      'dsid' => 'MODS',
      'title_field' => ['titleInfo', 'title'],
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ],
  ];
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_video_islandora_sp_videocmodel_islandora_view_object($object, $page_number, $page_size) {
  // @FIXME
// theme() has been renamed to _theme() and should NEVER be called directly.
// Calling _theme() directly can alter the expected output and potentially
// introduce security issues (see https://www.drupal.org/node/2195739). You
// should use renderable arrays instead.
//
//
// @see https://www.drupal.org/node/2195739
// $output = theme('islandora_video', array('object' => $object));

  return array('' => $output);
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_video_islandora_sp_videocmodel_islandora_ingest_steps() {
  return [
    'islandora_video_upload' => [
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_video_upload_form',
      'module' => 'islandora_video',
      'file' => 'includes/video_upload.form.inc',
    ],
  ];
}

/**
 * Implements hook_islandora_CMODEL_PID_derivative().
 */
function islandora_video_islandora_sp_videocmodel_islandora_derivative() {
  $derivatives = [];
  if (\Drupal::config('islandora_video.settings')->get('islandora_video_make_thumbnail_locally')) {
    $derivatives[] = [
      'source_dsid' => 'OBJ',
      'destination_dsid' => 'TN',
      'weight' => '0',
      'function' => [
        'islandora_video_create_thumbnail',
      ],
      'file' => drupal_get_path('module', 'islandora_video') . '/includes/derivatives.inc',
    ];
  }
  if (\Drupal::config('islandora_video.settings')->get('islandora_video_make_mp4_locally')) {
    $derivatives[] = [
      'source_dsid' => 'OBJ',
      'destination_dsid' => 'MP4',
      'weight' => '1',
      'function' => [
        'islandora_video_create_mp4',
      ],
      'file' => drupal_get_path('module', 'islandora_video') . '/includes/derivatives.inc',
    ];
  }
  if (\Drupal::config('islandora_video.settings')->get('islandora_video_make_ogg_locally')) {
    $derivatives[] = [
      'source_dsid' => 'OBJ',
      'destination_dsid' => 'OGG',
      'weight' => '2',
      'function' => [
        'islandora_video_create_ogg',
      ],
      'file' => drupal_get_path('module', 'islandora_video') . '/includes/derivatives.inc',
    ];
  }
  if (\Drupal::config('islandora_video.settings')->get('islandora_video_make_archive')) {
    $derivatives[] = [
      'source_dsid' => 'OBJ',
      'destination_dsid' => 'MKV',
      'weight' => '3',
      'function' => [
        'islandora_video_create_mkv',
      ],
      'file' => drupal_get_path('module', 'islandora_video') . '/includes/derivatives.inc',
    ];
  }
  return $derivatives;
}

/**
 * Implements hook_file_mimetype_mapping_alter().
 */
function islandora_video_file_mimetype_mapping_alter(&$mapping) {
  // Make sure the mapping is sensible for video/mp4 by removing
  // it from array and adding it to end so it has priority.
  $code = $mapping['extensions']['mp4'];
  unset($mapping['extensions']['mp4']);
  $mapping['extensions']['mp4'] = $code;
}
